name: draggable_flutter_list
description: a flutter list view which can drag & move item to change order.
version: 1.0.4+1
author: Realank <realank@126.com>
homepage: https://github.com/Realank/draggable_flutter_list

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
